# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import engine_control_pb2 as proto_dot_engine__control__pb2


class EngineControllerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ControlEngine = channel.unary_unary(
        '/maum.brain.EngineController/ControlEngine',
        request_serializer=proto_dot_engine__control__pb2.ControlRequest.SerializeToString,
        response_deserializer=proto_dot_engine__control__pb2.ControlResponse.FromString,
        )


class EngineControllerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ControlEngine(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EngineControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ControlEngine': grpc.unary_unary_rpc_method_handler(
          servicer.ControlEngine,
          request_deserializer=proto_dot_engine__control__pb2.ControlRequest.FromString,
          response_serializer=proto_dot_engine__control__pb2.ControlResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'maum.brain.EngineController', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
