# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import nsg_pb2 as proto_dot_nsg__pb2


class GptTextGenStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Gen = channel.unary_unary(
        '/gpt.nsg.GptTextGen/Gen',
        request_serializer=proto_dot_nsg__pb2.InputText.SerializeToString,
        response_deserializer=proto_dot_nsg__pb2.Outputs.FromString,
        )


class GptTextGenServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Gen(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GptTextGenServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Gen': grpc.unary_unary_rpc_method_handler(
          servicer.Gen,
          request_deserializer=proto_dot_nsg__pb2.InputText.FromString,
          response_serializer=proto_dot_nsg__pb2.Outputs.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gpt.nsg.GptTextGen', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
